// נתוני ייבוא ראשוני לציוד משרדי - שני ספקים: "עולם המדבקות" (מדבקות) ו"גוונים" (ציוד משרדי כללי)
// נערם חד-פעמית דרך דגל ב-settings (ראה db.js) - לא ידרוס פריטים שנוספו/נערכו ידנית
const OFFICE_SUPPLIES_SEED = {
  "עולם המדבקות": [
    { item_name: "מדבקות 8 בשורה - דף אחיד, זהב", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, כסף", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - 32 דפים באריזה", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, אדום", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, כחול", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, צהוב", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, כתום", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, סגול", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, ירוק", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, חום", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - דף אחיד, וורוד", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 8 בשורה - צבעוני", category: "מדבקות 8 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, זהב", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, כסף", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - 32 דפים באריזה", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, אדום", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, כחול", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, צהוב", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, כתום", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, סגול", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, ירוק", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, חום", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - דף אחיד, וורוד", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 11 בשורה - צבעוני", category: "מדבקות 11 בשורה" },
    { item_name: "מדבקות 12 בשורה - דף אחיד, זהב", category: "מדבקות 12 בשורה" },
    { item_name: "מדבקות 12 בשורה - דף אחיד, כסף", category: "מדבקות 12 בשורה" },
    { item_name: "מדבקות 12 בשורה - 32 דפים באריזה", category: "מדבקות 12 בשורה" },
    { item_name: "מדבקות 4 בשורה - 32 דפים באריזה", category: "מדבקות 4 בשורה" },
    { item_name: "מדבקות 6 בשורה - 32 דפים באריזה", category: "מדבקות 6 בשורה" },
    { item_name: "מדבקות 6 בשורה - צבע אחיד", category: "מדבקות 6 בשורה" },
    { item_name: "מדבקות 2 בשורה - דף אחיד, כסף", category: "מדבקות 2 בשורה" },
  ],
  "גוונים": [
    { item_name: "אקדח דבק חם (איכותי)", category: null },
    { item_name: "ביצי קלקר (קטן)", category: null },
    { item_name: "גומיות מס' 20 (איכותי)", category: null },
    { item_name: "גומיות מס' 22 (איכותי)", category: null },
    { item_name: "גפרורים טבעי (100 גר')", category: null },
    { item_name: "דבק דו צדדי (דק)", category: null },
    { item_name: "דבק דו צדדי (ספוג) 1.5", category: null },
    { item_name: "דבק סטיק גדול (21 גר') - UHU", category: null },
    { item_name: "דבק סלוטייפ - רגיל - 8 יח' בשרוול", category: null },
    { item_name: "דבק סלוטייפ - רחב", category: null },
    { item_name: "דבק פלסטיק גדול עם פיה", category: null },
    { item_name: "דבק פלסטיק קטן עם פיה", category: null },
    { item_name: "דבק תיק תק - בלו טק", category: null },
    { item_name: "דיו לחותמת - אדום", category: null },
    { item_name: "דיו לחותמת - כחול", category: null },
    { item_name: "דיו לחותמת - סגול", category: null },
    { item_name: "דיו לחותמת - שחור", category: null },
    { item_name: "דפדפת שורות (10 במארז) A5", category: null },
    { item_name: "דפי ממו (צבעוני)", category: null },
    { item_name: "חב' להבים לסכין יפני - להב צר", category: null },
    { item_name: "חב' להבים לסכין יפני - להב רחב", category: null },
    { item_name: "טוש ארטליין דק למשרד- אדום", category: null },
    { item_name: "טוש ארטליין דק למשרד- שחור", category: null },
    { item_name: "טוש ארטליין - צבע שחור - ראש שפיץ", category: null },
    { item_name: "טוש ארטליין - צבע שחור - ראש רחב", category: null },
    { item_name: "טוש מחיק ארטליין - צבע אדום - ראש שפיץ", category: null },
    { item_name: "טוש מחיק ארטליין - צבע ירוק - ראש שפיץ", category: null },
    { item_name: "טוש מחיק ארטליין - צבע כחול - ראש שפיץ", category: null },
    { item_name: "טוש מחיק ארטליין - צבע סגול - ראש שפיץ", category: null },
    { item_name: "טוש מחיק ארטליין - צבע שחור - ראש שפיץ", category: null },
    { item_name: "טיפקס מברשת/ספוג", category: null },
    { item_name: "טיפקס עט", category: null },
    { item_name: "לורד 36 יח' בחבילה - פיבראקולור בלבד", category: null },
    { item_name: "למינציה A3 - TRIPLE - טריפל", category: null },
    { item_name: "למינציה A4 - TRIPLE - טריפל", category: null },
    { item_name: "מחברת חשבון - 10 יחי' במארז", category: null },
    { item_name: "מחברת שורות (14 שורות) - 10 יחי' במארז", category: null },
    { item_name: "מחברת שורות (10 שורות) - 10 יחי' במארז", category: null },
    { item_name: "מחדד מתכת ידני גרמני - 3 / 4 במארז", category: null },
    { item_name: "מחק איכותי (10 יחי' בחב') - סטדלר", category: null },
    { item_name: "מחק ללוח מחיק (איכותי) - ארטליין", category: null },
    { item_name: "מנקה מקטרות צבע לבן", category: null },
    { item_name: "מספריים גדולות (איכותי)", category: null },
    { item_name: "מספריים קטנות - לא פלסטיק שקוף", category: null },
    { item_name: "מקלות ארטיק טבעי (200 גר') - לא צבעוני", category: null },
    { item_name: "מרקר ורוד יחיד - job / סטדלר", category: null },
    { item_name: "מרקר צהוב יחיד - job / סטדלר", category: null },
    { item_name: "מתקן לדבק סלוטייפ (מיני כבד)", category: null },
    { item_name: "מתקן לדפי ממו (רשת מתכת)", category: null },
    { item_name: "ניילוניות קלסר A4 (פוליו) - 30 מיקרון (קרטון)", category: null },
    { item_name: "ניילוניות קלסר A5 - 30 מיקרון", category: null },
    { item_name: "נעצים ללוח שעם", category: null },
    { item_name: "נרות דבק חם (איכותי)", category: null },
    { item_name: "סיכה מתפצלת - קטן (מס' 1)", category: null },
    { item_name: "סיכות בטחון (בינוני)", category: null },
    { item_name: "סיכות בטחון (גדול)", category: null },
    { item_name: "סיכות לשדכן 26/6 - קנגרו", category: null },
    { item_name: "סיכות משרד מס' 5", category: null },
    { item_name: "סכין יפני איכותי", category: null },
    { item_name: "סכין יפני איכותי - (צר)", category: null },
    { item_name: "סקוטש זכר - BIG", category: null },
    { item_name: "סקוטש נקבה - BIG", category: null },
    { item_name: "סרגל מתכת 15 ס\"מ", category: null },
    { item_name: "סרגל מתכת 30 ס\"מ", category: null },
    { item_name: "סרגל מתכת 50 ס\"מ", category: null },
    { item_name: "עטים כדורי כחול - אקסטא אופיס/גריפ טנפון", category: null },
    { item_name: "עיניים זזות 7 מ\"מ / 8 מ\"מ", category: null },
    { item_name: "עינים זזות 10 מ\"מ", category: null },
    { item_name: "עפרונות סטדלר (12 יחי' במארז)", category: null },
    { item_name: "פלסטלינה - צבע חום", category: null },
    { item_name: "פלסטלינה - צבע ירוק בהיר", category: null },
    { item_name: "פלסטלינה - צבע ירוק כהה", category: null },
    { item_name: "פלסטלינה - צבע צהוב", category: null },
    { item_name: "פלסטלינה - צבע ורוד", category: null },
    { item_name: "פלסטלינה - צבע כתום", category: null },
    { item_name: "פלסטלינה - צבע תכלת", category: null },
    { item_name: "פלסטלינה - צבע לבן", category: null },
    { item_name: "פלסטלינה - צבע אפור", category: null },
    { item_name: "פלסטלינה - צבע אדום", category: null },
    { item_name: "פתקים נדבקים (ממו)", category: null },
    { item_name: "צבעי ילדים (12 יח' בחבילה) - BIC", category: null },
    { item_name: "צבעי פסטל - פסטל", category: null },
    { item_name: "קלסר פשוט רחב - עם מנוף", category: null },
    { item_name: "שדכן סיכות 26/6 - קנגרו", category: null },
    { item_name: "שקף איכותי למ. צילום - TRIPLE - טריפל", category: null },
  ],
};

module.exports = { OFFICE_SUPPLIES_SEED };